require 'test/unit'
require_relative './test_naive_bayes_classifier'
require_relative './test_naive_bayes_em'
require_relative './test_language_detector'
require_relative './test_tweet_language_detection'